### ISSUE TITLE
disabled library placed into META

### ISSUE THREAD

**Issue by olafhering** [ocaml/oasis#116]
After upgrading [Chris00/ocaml-csv](https://github.com/Chris00/ocaml-csv)  from version 1.5 to 1.7 the resulting META file has a subpackage 'lwt", even with --disable-lwt. The lwt is not built, so I think it should not be part of the META file for ocamlfind.

**Comment by Chris00** [comment]
On 2017-07-19, Olaf Hering wrote:
>
> After upgrading Chris00/ocaml-csv from version 1.5 to 1.7 the resulting META file has a subpackage 'lwt", even with --disable-lwt. The lwt is not built, so I think it should not be part of the META file for ocamlfind.

No big problem because of the line

   exists_if = "csv_lwt.cma"

**Comment by olafhering** [comment]
In openSUSE it creates a rpm dependency to ocamlfind(lwt), which does not exist. As a result, virt-top gets into state `unresolvable: nothing provides ocamlfind(lwt) needed by ocaml-csv-devel`

**Comment by gildor478** [comment]
There is another bug/feature request for that:
https://forge.ocamlcore.org/tracker/?group_id=54&atid=294&func=detail&aid=547

The problem is to be able to generate the META file at compile time, rather than when releasing the library.

I have no good solution and will update the other bug when I have one.

For openSUSE, I think they should take into account the "exist_if" condition which is part of the standard META directive.

**Comment by olafhering** [comment]
I used `sed -i '/^Library csv_lwt/,/^$/d' _oasis` for the time being. I will see how to integrate "exist_if" into the dependency generator. Thanks.

**Comment by Chris00** [comment]
Note that, when [sub-packages are supported](https://github.com/ocaml/oasis/issues/108), the `csv` library is likely to be split into `csv` and `csv-lwt`.
