### ISSUE TITLE
parametrized plugin tags do not work on windows 

### ISSUE THREAD

**Issue by ygrek** [ocaml/oasis#122]
witness https://ci.appveyor.com/project/ygrek/sqlgg/build/1.0.5 (build of https://github.com/ygrek/sqlgg/tree/415c05c6116177e01eb6a712426743dd0d787c04)
`_oasis` contains : 
```
AlphaFeatures: ocamlbuild_more_args
XOCamlbuildPluginTags: package(mybuild)
```
and generated `setup.ml` has : 
```
     build =
       OCamlbuildPlugin.build
         ["-use-ocamlfind"; "-plugin-tags"; "'package(mybuild)'"; "-j"; "0"];
```
which breaks build on windows. Manually removing single quotes breaks build on linux. Supposely quoting in `OASISExec.run` is too naive.

oasis version 0.4.10

**Comment by gildor478** [comment]
Working on this issue and I will fix it this week.

It seems that the problem is that in OCamlbuildCommon the "package(mybuild)" is quoted by default, rather than using `Filename.quote` at runtime. 

The solution is to move the quoted argument of the `extra_args_ocamlbuild_common` (compile time function) to `fix_args` (runtime function) in OCamlbuildCommon.

`OASISExec.run` is actually simple, it only quotes the program name and left the argument untouched because they are supposed to be quoted before.

Will you have time to test later this week?

**Comment by ygrek** [comment]
it is tested by appveyor CI, so I should be able to rerun build, yes

**Comment by gildor478** [comment]
PR for opam:
ocaml/opam-repository#11723

**Comment by ygrek** [comment]
Sorry for late reply. Confirmed, fix works, thanks a lot!
